export const dummyAppState = {
    currentUser: {
        user_id: 1,
        username: "lily_pink",
        email: "123",
        password_hash: "123",
        first_name: "Лиля",
        last_name: "Моя",
        phone_number: "+1234567890",
        role: "customer",
        created_at: "2026-04-10T10:00:00Z",
        updated_at: null,
        deleted_at: null,
        isRegistered: false,
        isAuthorized: false,

        cart: [
            {
                product_id: 10,
                quantity: 2,
                created_at: "2026-04-12T15:30:00Z",
            },
        ],

        orders: [
            {
                order_id: 101,
                status: "pending",
                pickup_point_id: 1,
                payment_method_id: 1,
                total_amount: 3000.0,
                created_at: "2026-04-13T02:00:00Z",
                updated_at: null,
                is_hidden: false,
                items: [
                    {
                        product_id: 10,
                        quantity: 2,
                        price_snapshot: 1500.0,
                    },
                ],
            },
        ],

        pickup_codes: [
            {
                code: "A1B2",
                expires_at: "2026-04-20T12:00:00Z",
            },
        ],
    },

    products: [
        {
            product_id: 1,
            name: "Базовая футболка оверсайз",
            description: "Идеальная основа для твоих принтов.",
            category_id: 1,
            supplier_id: 1,
            is_base: true,
            is_custom: false,
            front_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            back_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            gallery: [],
            created_at: "18.04.2026",
        },
        {
            product_id: 2,
            name: "Классическое худи",
            description: "Теплое худи под кастом.",
            category_id: 2,
            supplier_id: 2,
            is_base: true,
            is_custom: false,
            front_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            back_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            gallery: [],
            created_at: "18.04.2026",
        },
        {
            product_id: 3,
            name: "Этническое платье",
            description: "Платье из легкой ткани.",
            category_id: 3,
            supplier_id: 1,
            is_base: false,
            is_custom: false,
            front_photo: null,
            back_photo: null,
            gallery: [
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            ],
            created_at: "10.04.2026",
        },
        {
            product_id: 4,
            name: "Худи 'Ночная тень'",
            description: "Кастомный заказ.",
            category_id: 2,
            supplier_id: 2,
            is_base: false,
            is_custom: true,
            front_photo: null,
            back_photo: null,
            gallery: [
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            ],
            created_at: "19.04.2026",
        },
        {
            product_id: 5,
            name: "Свитшот базовый",
            description: "Основа без капюшона.",
            category_id: 2,
            supplier_id: 1,
            is_base: true,
            is_custom: false,
            front_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            back_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            gallery: [],
            created_at: "15.04.2026",
        },
        {
            product_id: 6,
            name: "Футболка приталенная",
            description: "Женская базовая футболка.",
            category_id: 1,
            supplier_id: 2,
            is_base: true,
            is_custom: false,
            front_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            back_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            gallery: [],
            created_at: "16.04.2026",
        },
        {
            product_id: 7,
            name: "Готический лонгслив",
            description: "Сложный принт.",
            category_id: 2,
            supplier_id: 1,
            is_base: false,
            is_custom: false,
            front_photo: null,
            back_photo: null,
            gallery: [
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            ],
            created_at: "12.04.2026",
        },
        {
            product_id: 8,
            name: "Платье-комбинация",
            description: "Шелковое наслаждение.",
            category_id: 3,
            supplier_id: 2,
            is_base: false,
            is_custom: false,
            front_photo: null,
            back_photo: null,
            gallery: [
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            ],
            created_at: "11.04.2026",
        },
        {
            product_id: 9,
            name: "Футболка 'Дарк Соул'",
            description: "Твой кастом.",
            category_id: 1,
            supplier_id: 1,
            is_base: false,
            is_custom: true,
            front_photo: null,
            back_photo: null,
            gallery: [
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            ],
            created_at: "18.04.2026",
        },
        {
            product_id: 10,
            name: "Кроп-топ базовый",
            description: "Укороченная основа.",
            category_id: 1,
            supplier_id: 2,
            is_base: true,
            is_custom: false,
            front_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            back_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            gallery: [],
            created_at: "17.04.2026",
        },
        {
            product_id: 11,
            name: "Толстовка на молнии",
            description: "Основа с зиппером.",
            category_id: 2,
            supplier_id: 1,
            is_base: true,
            is_custom: false,
            front_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            back_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            gallery: [],
            created_at: "14.04.2026",
        },
        {
            product_id: 12,
            name: "Летнее платье в горошек",
            description: "Легкость и стиль.",
            category_id: 3,
            supplier_id: 2,
            is_base: false,
            is_custom: false,
            front_photo: null,
            back_photo: null,
            gallery: [
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            ],
            created_at: "09.04.2026",
        },
        {
            product_id: 13,
            name: "Кастом худи 'Дракон'",
            description: "Творение пользователя.",
            category_id: 2,
            supplier_id: 1,
            is_base: false,
            is_custom: true,
            front_photo: null,
            back_photo: null,
            gallery: [
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            ],
            created_at: "20.04.2026",
        },
        {
            product_id: 14,
            name: "Юбка-миди базовая",
            description: "Для кастомизации низа.",
            category_id: 3,
            supplier_id: 2,
            is_base: true,
            is_custom: false,
            front_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            back_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            gallery: [],
            created_at: "13.04.2026",
        },
        {
            product_id: 15,
            name: "Свитер оверсайз",
            description: "Теплая основа.",
            category_id: 2,
            supplier_id: 1,
            is_base: true,
            is_custom: false,
            front_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            back_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            gallery: [],
            created_at: "10.04.2026",
        },
        {
            product_id: 16,
            name: "Майка алкоголичка",
            description: "Тонкая база.",
            category_id: 1,
            supplier_id: 2,
            is_base: true,
            is_custom: false,
            front_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            back_photo:
                "https://i.pinimg.com/736x/29/00/dc/2900dcc3535786730e364e31f8b4155d.jpg",
            gallery: [],
            created_at: "08.04.2026",
        },
        {
            product_id: 17,
            name: "Платье вечернее",
            description: "Для выхода в свет.",
            category_id: 3,
            supplier_id: 1,
            is_base: false,
            is_custom: false,
            front_photo: null,
            back_photo: null,
            gallery: [
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            ],
            created_at: "05.04.2026",
        },
        {
            product_id: 18,
            name: "Футболка 'Лили'",
            description: "Твой личный шедевр.",
            category_id: 1,
            supplier_id: 2,
            is_base: false,
            is_custom: true,
            front_photo: null,
            back_photo: null,
            gallery: [
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            ],
            created_at: "21.04.2026",
        },
    ],

    prices: [
        {
            price_id: 1,
            product_id: 1,
            price: 1200,
            created_at: "01.01.2026",
            is_active: false,
        },
        {
            price_id: 2,
            product_id: 1,
            price: 1350,
            created_at: "15.01.2026",
            is_active: false,
        },
        {
            price_id: 3,
            product_id: 1,
            price: 1300,
            created_at: "10.02.2026",
            is_active: false,
        },
        {
            price_id: 4,
            product_id: 1,
            price: 1500,
            created_at: "01.03.2026",
            is_active: false,
        },
        {
            price_id: 5,
            product_id: 1,
            price: 1450,
            created_at: "15.03.2026",
            is_active: false,
        },
        {
            price_id: 6,
            product_id: 1,
            price: 1600,
            created_at: "05.04.2026",
            is_active: false,
        },
        {
            price_id: 7,
            product_id: 1,
            price: 1750,
            created_at: "18.04.2026",
            is_active: true,
        }, // Текущая

        {
            price_id: 8,
            product_id: 2,
            price: 3500,
            created_at: "10.04.2026",
            is_active: false,
        },
        {
            price_id: 9,
            product_id: 2,
            price: 3800,
            created_at: "18.04.2026",
            is_active: true,
        },

        {
            price_id: 10,
            product_id: 3,
            price: 4200,
            created_at: "10.04.2026",
            is_active: true,
        },
        {
            price_id: 11,
            product_id: 5,
            price: 2900,
            created_at: "15.04.2026",
            is_active: true,
        },
    ],

    dictionaries: {
        categories: [
            { category_id: 1, name: "Футболки" },
            { category_id: 2, name: "Худи" },
            { category_id: 3, name: "Платья" },
        ],
        sizes: [
            { size_id: 1, size_value: "XS" },
            { size_id: 2, size_value: "S" },
            { size_id: 3, size_value: "M" },
            { size_id: 4, size_value: "L" },
            { size_id: 5, size_value: "XL" },
            { size_id: 6, size_value: "Oversize" },
        ],
        payment_methods: [
            { payment_method_id: 1, name: "Банковская карта", is_active: true },
            {
                payment_method_id: 2,
                name: "СБП (Система быстрых платежей)",
                is_active: true,
            },
            { payment_method_id: 3, name: "При получении", is_active: false },
        ],
        pickup_points: [
            {
                pickup_point_id: 1,
                city: "Москва",
                street: "Тверская",
                building: "12",
                created_at: "01.01.2026",
                deleted_at: null,
            },
            {
                pickup_point_id: 2,
                city: "Санкт-Петербург",
                street: "Невский проспект",
                building: "45",
                created_at: "15.02.2026",
                deleted_at: null,
            },
            {
                pickup_point_id: 3,
                city: "Казань",
                street: "Баумана",
                building: "8",
                created_at: "20.03.2026",
                deleted_at: "2026-04-10T12:00:00Z",
            },
        ],

        // Поставщики
        suppliers: [
            {
                supplier_id: 1,
                name: "Ткани Империум",
                email: "supply@imperium.com",
                details: "Поставщик премиального хлопка",
                created_at: "2026-01-01T00:00:00Z",
                updated_at: null,
                deleted_at: null,
            },
        ],
        // Точки самовывоза
    },
    categories: [
        { category_id: 1, name: "Футболки" },
        { category_id: 2, name: "Худи" },
        { category_id: 3, name: "Платья" },
    ],
    sizes: [
        { size_id: 1, size_value: "XS" },
        { size_id: 2, size_value: "S" },
        { size_id: 3, size_value: "M" },
        { size_id: 4, size_value: "L" },
        { size_id: 5, size_value: "XL" },
        { size_id: 6, size_value: "Oversize" },
    ],
    payment_methods: [
        { payment_method_id: 1, name: "Банковская карта", is_active: true },
        {
            payment_method_id: 2,
            name: "СБП (Система быстрых платежей)",
            is_active: true,
        },
        { payment_method_id: 3, name: "При получении", is_active: false },
    ],
    pickup_points: [
        {
            pickup_point_id: 1,
            city: "Москва",
            street: "Тверская",
            building: "12",
            created_at: "01.01.2026",
            deleted_at: null,
        },
        {
            pickup_point_id: 2,
            city: "Санкт-Петербург",
            street: "Невский проспект",
            building: "45",
            created_at: "15.02.2026",
            deleted_at: null,
        },
        {
            pickup_point_id: 3,
            city: "Казань",
            street: "Баумана",
            building: "8",
            created_at: "20.03.2026",
            deleted_at: "2026-04-10T12:00:00Z",
        },
    ],

    orders: [
        {
            order_id: 5001,
            user_id: 1,
            username: "lily_pink",
            status: "Создан",
            order_date: "18.04.2026",
            total_amount: 4500,
            pickup_point: "Москва, ул. Тверская, д. 12",
            payment_method: "Банковская карта",
            items: [
                {
                    product_id: 1,
                    name: "Базовая футболка оверсайз",
                    quantity: 1,
                    price: 1750,
                },
                {
                    product_id: 2,
                    name: "Классическое худи",
                    quantity: 1,
                    price: 2750,
                },
            ],
        },
        {
            order_id: 5002,
            user_id: 3,
            username: "toxic_girl",
            status: "Собирается",
            order_date: "16.04.2026",
            total_amount: 4200,
            pickup_point: "Санкт-Петербург, Невский проспект, д. 45",
            payment_method: "СБП (Система быстрых платежей)",
            items: [
                {
                    product_id: 3,
                    name: "Этническое платье",
                    quantity: 1,
                    price: 4200,
                },
            ],
        },
        {
            order_id: 5003,
            user_id: 5,
            username: "sweet_candy",
            status: "Готов к выдаче",
            order_date: "15.04.2026",
            total_amount: 5800,
            pickup_point: "Москва, ул. Тверская, д. 12",
            payment_method: "При получении",
            items: [
                {
                    product_id: 5,
                    name: "Свитшот базовый",
                    quantity: 2,
                    price: 2900,
                },
            ],
        },
        {
            order_id: 5004,
            user_id: 9,
            username: "pro_gamer",
            status: "Получен",
            order_date: "10.04.2026",
            total_amount: 3800,
            pickup_point: "Казань, ул. Баумана, д. 8",
            payment_method: "Банковская карта",
            items: [
                {
                    product_id: 4,
                    name: "Худи 'Ночная тень'",
                    quantity: 1,
                    price: 3800,
                },
            ],
        },
        {
            order_id: 5005,
            user_id: 10,
            username: "sad_boy",
            status: "Отменен",
            order_date: "12.04.2026",
            total_amount: 1750,
            pickup_point: "Санкт-Петербург, Невский проспект, д. 45",
            payment_method: "Банковская карта",
            items: [
                {
                    product_id: 1,
                    name: "Базовая футболка оверсайз",
                    quantity: 1,
                    price: 1750,
                },
            ],
        },
        {
            order_id: 5006,
            user_id: 4,
            username: "night_rider",
            status: "Создан",
            order_date: "19.04.2026",
            total_amount: 8500,
            pickup_point: "Москва, ул. Тверская, д. 12",
            payment_method: "СБП (Система быстрых платежей)",
            items: [
                {
                    product_id: 7,
                    name: "Готический лонгслив",
                    quantity: 1,
                    price: 4500,
                },
                {
                    product_id: 11,
                    name: "Толстовка на молнии",
                    quantity: 1,
                    price: 4000,
                },
            ],
        },
    ],
    reviews: [
        {
            review_id: 1,
            product_id: 1,
            username: "sweet_candy",
            rating: 5,
            review_text: "Отличная футболка, качество супер!",
            created_at: "18.04.2026",
        },
        {
            review_id: 2,
            product_id: 2,
            username: "toxic_girl",
            rating: 1,
            review_text:
                "Ужасный крой! Нитки торчат, стирку не пережило. Вы все тут мошенники и твари!",
            created_at: "19.04.2026",
        },
        {
            review_id: 3,
            product_id: 3,
            username: "fashion_diva",
            rating: 4,
            review_text: "Платье красивое, но немного маломерит.",
            created_at: "20.04.2026",
        },
        {
            review_id: 4,
            product_id: 1,
            username: "random_dude",
            rating: 2,
            review_text:
                "Что за бред, почему так дорого за кусок ткани? Я вашу контору труба шатал.",
            created_at: "21.04.2026",
        },
    ],
    custom_designs: [
        {
            design_id: 1,
            product_id: 4,
            username: "lily_pink",
            file_path:
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            created_at: "19.04.2026",
            deleted_at: null,
        },
        {
            design_id: 2,
            product_id: 9,
            username: "dark_lord",
            file_path:
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            created_at: "20.04.2026",
            deleted_at: null,
        },
        {
            design_id: 3,
            product_id: 13,
            username: "toxic_girl",
            file_path:
                "https://i.pinimg.com/736x/81/eb/7a/81eb7a8dd4bbd4720ad2ed935b4d3c4b.jpg",
            created_at: "21.04.2026",
            deleted_at: "2026-04-22T10:00:00Z",
        },
    ],

    cart_items: [
        {
            cart_item_id: 1,
            user_id: 1,
            product_id: 1,
            quantity: 2,
            created_at: "20.04.2026",
        },
        {
            cart_item_id: 2,
            user_id: 1,
            product_id: 3,
            quantity: 1,
            created_at: "21.04.2026",
        },
        {
            cart_item_id: 3,
            user_id: 1,
            product_id: 4,
            quantity: 1,
            created_at: "22.04.2026",
        },
    ],
};
