export const mockUsers = [
    {
        _id: 1,
        username: "johndoe",
        email: "johndoe@example.com",
        password_hash: "pass123",
        first_name: "Джон",
        last_name: "Доу",
        phone_number: "+79991112233",
        role: "customer",
        created_at: "2026-05-30T12:00:00Z",
        updated_at: null,
        deleted_at: null,
        cart_items: [
            {
                product_id: 1,
                quantity: 2,
                created_at: "2026-05-30T15:30:00Z",
            },
        ],
    },
    {
        _id: 2,
        username: "janedoe",
        email: "janedoe@example.com",
        password_hash: "pass123",
        first_name: "Джейн",
        last_name: "Доу",
        phone_number: "88005553535",
        role: "admin",
        created_at: "2026-05-30T12:00:00Z",
        updated_at: null,
        deleted_at: null,
        cart_items: [
            {
                product_id: 2,
                quantity: 2,
                created_at: "2026-05-30T15:30:00Z",
            },
        ],
    },
    {
        _id: 3,
        username: "kris",
        email: "kristine@example.com",
        password_hash: "pass123",
        first_name: "Крис",
        last_name: "Доу",
        phone_number: "+79991112233",
        role: "customer",
        created_at: "2026-05-30T12:00:00Z",
        updated_at: null,
        deleted_at: null,
        cart_items: [
            {
                product_id: 3,
                quantity: 2,
                created_at: "2026-05-30T15:30:00Z",
            },
        ],
    },
    {
        _id: 4,
        username: "sam",
        email: "sammy@example.com",
        password_hash: "pass123",
        first_name: "Сэм",
        last_name: "Доу",
        phone_number: "+79991112233",
        role: "customer",
        created_at: "2026-05-30T12:00:00Z",
        updated_at: null,
        deleted_at: null,
        cart_items: [
            {
                product_id: 1,
                quantity: 2,
                created_at: "2026-05-30T15:30:00Z",
            },
        ],
    },
    {
        _id: 5,
        username: "damian",
        email: "damiano@example.com",
        password_hash: "pass123",
        first_name: "Дамиан",
        last_name: "Доу",
        phone_number: "+79991112233",
        role: "admin",
        created_at: "2026-05-30T12:00:00Z",
        updated_at: null,
        deleted_at: null,
        cart_items: [
            {
                product_id: 2,
                quantity: 2,
                created_at: "2026-05-30T15:30:00Z",
            },
        ],
    },
    {
        _id: 6,
        username: "dan",
        email: "daniel@example.com",
        password_hash: "pass123",
        first_name: "Дэниед",
        last_name: "Доу",
        phone_number: "+79991112233",
        role: "customer",
        created_at: "2026-05-30T12:00:00Z",
        updated_at: null,
        deleted_at: null,
        cart_items: [
            {
                product_id: 3,
                quantity: 2,
                created_at: "2026-05-30T15:30:00Z",
            },
        ],
    },
    {
        _id: 7,
        username: "mark",
        email: "markus@example.com",
        password_hash: "pass123",
        first_name: "Марк",
        last_name: "Доу",
        phone_number: "+79991112233",
        role: "customer",
        created_at: "2026-05-30T12:00:00Z",
        updated_at: null,
        deleted_at: null,
        cart_items: [
            {
                product_id: 1,
                quantity: 2,
                created_at: "2026-05-30T15:30:00Z",
            },
        ],
    },
    {
        _id: 8,
        username: "lilya",
        email: "lilyanna@example.com",
        password_hash: "pass123",
        first_name: "Лилианна",
        last_name: "Доу",
        phone_number: "+79991112233",
        role: "customer",
        created_at: "2026-05-30T12:00:00Z",
        updated_at: null,
        deleted_at: null,
        cart_items: [
            {
                product_id: 2,
                quantity: 2,
                created_at: "2026-05-30T15:30:00Z",
            },
        ],
    },
    {
        _id: 9,
        username: "jas",
        email: "jasmin@example.com",
        password_hash: "pass123",
        first_name: "Жасмин",
        last_name: "Доу",
        phone_number: "+79991112233",
        role: "customer",
        created_at: "2026-05-30T12:00:00Z",
        updated_at: null,
        deleted_at: null,
        cart_items: [
            {
                product_id: 3,
                quantity: 2,
                created_at: "2026-05-30T15:30:00Z",
            },
        ],
    },
    {
        _id: 10,
        username: "emily",
        email: "emillya@example.com",
        password_hash: "pass123",
        first_name: "Эмили",
        last_name: "Доу",
        phone_number: "+79991112233",
        role: "customer",
        created_at: "2026-05-30T12:00:00Z",
        updated_at: null,
        deleted_at: null,
        cart_items: [
            {
                product_id: 1,
                quantity: 2,
                created_at: "2026-05-30T15:30:00Z",
            },
        ],
    },
];
